import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/B/index'
import Button from '@/components/A/Buttonindex'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <Image src={'/Images/Xtwiter.jpeg'} alt=" x logo" width={100} height={100}/>
        <h1>Happening now</h1>
        <h2>Join today.</h2>
        <Button/>
      </main>
      <Footer/>
    </>
  )
}
